### PR TITLE
[MINOR] Ensure the local `invoke-release-{}-{}` branch is deleted after pushing it to `origin`

### PR DESCRIPTION
**Pull request by bar**

### CODE REVIEW

**Comment by nickwilliams-eventbrite** [comment]
I have concerns about this, @bar. When I used IR right now with this config, it is already checking out master. It's not deleting the branch, but it's already checking out master. Your change makes it check out master and then delete the branch. So either you're checking out master twice (your second checkout here can be removed), or the flow isn't quite right. Can you please revise?

**Comment by bar** [comment]
I'm not entirely sure what you mean @nickwilliams-eventbrite , can you paste the log so I can take a look?

there are 2 places in the entire codebase that call `_checkout_branch(verbose, BRANCH_MASTER)` and they can't be called in the same work path, it is either one or the other

the only other place left calling `_checkout_branch` is meant to checkout to the current branch `_checkout_branch(verbose, current_branch_name)`, not `BRANCH_MASTER`

**Comment by nickwilliams-eventbrite** [comment]
I haven't released anything today, so I don't have a log handy. But ever since they changed to PR-based releases, my observation of the behavior every time is that, when it's done, it checks out `master`, which itself isn't even exactly correct (it should check out the branch upon which the release is based), but does not delete the release branch. `git status` after `invoke release` finishes always shows me on `master`.

**Comment by bar** [comment]
That's likely because you invoke release _from_ `master` meaning `current_branch_name` is `master`, so the last `_checkout_branch(verbose, current_branch_name)` is actually checking out to `master`, but the prior `_checkout_branch(verbose, BRANCH_MASTER)` needs to be done because `MASTER` is "guaranteed" to exist and we can't be checked out in the branch we are deleting.

I'll take a look on Monday but I think it is safe to remove `_checkout_branch(verbose, current_branch_name)` if we always release from `master`. Or we should avoid it if we are already in `master`.

**Comment by bar** [comment]
https://github.com/eventbrite/invoke-release/pull/26

**Pull request merged**
